### ISSUE TITLE
Migration to github created utter mess for downloads

### ISSUE THREAD

**Issue by quanah** [zeromq/zeromq4-1#129]
Please restore the old download site.  The process by which github creates releases is a god awful mess.

problem #1: Failure to create proper file names for source: -- v4.1.3.tar.gz rather than zeromq-4.1.3.tar.gz
problem #2: extracted source is a mess: tar xfz creates: zeromq4-1-4.1.3

**Comment by quanah** [comment]
New release download is missing configure, requires running autogen.sh

Please restore the old download site until you can actually provide working source releases.

**Comment by bluca** [comment]
The tarball and zip for the latest release are already fixed manually by @ewen-naos-nz a while ago:
https://github.com/zeromq/zeromq4-1/releases/tag/v4.1.4
https://github.com/zeromq/zeromq4-1/releases/download/v4.1.4/zeromq-4.1.4.tar.gz

For the next releases, they will be done automatically by Travis via https://github.com/zeromq/zeromq4-1/pull/126

**Comment by quanah** [comment]
Yes, I'm trying to keep my env consistent.  You've really made a mess of breaking older releases which may be in use by various distributions.  Dropping the original tarballs was very bad project management.

**Comment by bluca** [comment]
All current and old releases are still available, nothing was dropped, broken, or messed up.

http://zeromq.org/intro:get-the-software
https://zeromq.github.io/zeromq4-1/
http://lists.zeromq.org/pipermail/zeromq-dev/2016-May/030526.html
https://github.com/zeromq/zeromq4-1/issues/123
https://archive.org/search.php?query=subject%3A%22zeromq%22%20subject%3A%22message_queue%22

**Comment by somdoron** [comment]
@quanah in the mean time, I restored the download site, although it will take 8 hours to the dns to propagate, so check soon.

**Comment by quanah** [comment]
@bluca Ok, that was way down the page, although I finally found it.  I would suggest deleting the broken tarballs for old releases from github, and modifying the get-the-software page to have a link at the top for old releases.  @somdoron Thanks!

**Comment by bluca** [comment]
Github autogenerates tarballs and zip files from the repository when a tag is pushed, and they cannot be deleted.

**Comment by ewen-naos-nz** [comment]
@quanah @bluca: While the GitHub auto-generated ones (basically a tar/zip of the *git repository*) can't be deleted, it is possible to add *additional* files with all the bits that people "expect" to be there.  I did this by hand for the latest ZeroMQ 3.x and ZeroMQ 4.1 releases (but not older ones, because it's a time consuming manual step).  Apparently that wasn't enough versions, or maybe we need clearer documentation about which version to download.  ([@bluca has also volunteered to add those "ready to go" archives to a few more of the 4.1 older versions](https://github.com/zeromq/zeromq4-1/issues/123#issuecomment-224423130) -- thanks.)

In addition I've just (this afternoon) created:

https://github.com/imatix-legacy/zeromq-archived

which has the metadata needed to make a better replacement "download.zeromq.org" (once we find somewhere to host it), linking/redirecting to all the archives that were on download.zeromq.org.  (My intention is that this "metadata repository" would end up somewhere under the ZeroMQ GitHub page, but I don't have access to do that myself.)

The github.io view of that repository:

https://imatix-legacy.github.io/zeromq-archived/

has an index.html page rendered with links to everything (with the downloads served by archive.org); that too could be put somewhere more obvious to ZeroMQ downloaders.

Ewen

**Comment by bluca** [comment]
Older tarballs/zips have been uploaded to github, and download page was restored, closing.

**Comment by quanah** [comment]
thank you very much!
