### ISSUE TITLE
getsockopt only writes its own size instead of 'optvallen_'

### ISSUE THREAD

**Issue by rikvdh** [zeromq/zeromq4-1#52]
Hi,

Today I've spent a few hours raging at my code again, in the end getsockopt's odd behavior was the culprit.

I'm using getsockopt with ZMQ_RCVMORE and according the API-docs (http://api.zeromq.org/master:zmq-getsockopt#toc4) this value requires int64_t. So I'm passing a nice int64_t. But after a lot of debugging more never becomes 0. 

Looking at the implementation of libzmq:
https://github.com/zeromq/zeromq4-1/blob/3869d7d4902ecb41f20045b69750c272f413df0d/src/socket_base.cpp#L302-L310

It only checks for 'int'. So it never writes my full 64 bits. When more has a value of all 1's it is never overwritten.

So, the documentation is wrong about int64_t. And doesn't it make more sense to write the full 'optvallen_' instead of only 'sizeof(int)' bytes?  The documentation states it makes my variable zero.

Kind regards,

Rik

**Comment by hintjens** [comment]
That does indeed look like a documentation error. Ooops. Would you send a
fix?

**Comment by rikvdh** [comment]
@hintjens I now see that the documentation is ok for the 4-1 doc. http://api.zeromq.org/4-1:zmq-getsockopt#toc30

But what is your opinion about writing only 'sizeof(int)' instead of 'optvallen_' in getsockopt?

**Comment by hintjens** [comment]
Improving the code is always worth it...

**Comment by rikvdh** [comment]
Thanks @c-rack for the merge. :+1:

**Comment by pijyoi** [comment]
@rikvdh, the link you provided http://api.zeromq.org/master:zmq-getsockopt#toc4 is for zmq 2.2.0 (see top right corner of page)

Since, zmq 3.2.x, many of the options size got changed to "int".
http://api.zeromq.org/3-2:zmq-getsockopt

It is rather unfortunate that a simple google search will yield the 2.2.0 page. Which is a source of errors for quite a few of my colleagues.

In any case, since zmq 3.2.x, there is no need to get this particular socket option. Just use zmq_msg_more()

**Comment by hintjens** [comment]
@rikvdh, @c-rack next time let's make the fix on libzmq first, with an issue, then backport to stable. That is what our rules ask for (it takes out the risk of experimentation on stable releases, and lost patches.)

**Comment by c-rack** [comment]
@hintjens OK
